// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efqfljrvnovinoiopzoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmcWZsanJ2bm92aW5vaW9wem9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMTEwODUsImV4cCI6MjA2Mzc4NzA4NX0.vDsSq9Qn3CImKzcgNjRRN4w8avQ0tBEWEz6CyFPFl2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);